# /etc/bash/bashrc

# Proceed no further in the case of a non-interactive shell.
if [[ $- != *i* ]]; then
  return
fi

# Disable errexit in case the user enabled it then chose to re-source this file.
shopt -u -o errexit

# Disable completion when the input buffer is empty. Mute STDERR because this
# option is only present in the case that bash was built with readline support.
shopt -s no_empty_cmd_completion 2>/dev/null &&

  # Initialise PROMPT_COMMAND as an array, unless bash is acting as a login shell.
  # In the latter case, the profile.d drop-in will already have initialised it.
  shopt -q login_shell || PROMPT_COMMAND=()

# Don't let the user influence the order of sourcing for bash 5.3 or greater.
unset -v GLOBSORT
