0644 root root /etc/passwd
0644 root root /etc/passwd-
0644 root root /etc/group
0644 root root /etc/group-
0640 root shadow /etc/shadow
0640 root shadow /etc/shadow-
0640 root shadow /etc/gshadow
0640 root shadow /etc/gshadow-
0440 root root /etc/sudoers
0750 root root /etc/sudoers.d
0755 root root /etc/ssh
0600 root root /etc/ssh/sshd_config
0600 root root /etc/crontab
0600 root root /etc/cron.allow
0600 root root /etc/at.allow
0755 root root /etc/cron.d
0755 root root /etc/cron.daily
0755 root root /etc/cron.hourly
0755 root root /etc/cron.weekly
0755 root root /etc/cron.monthly
0755 root root /etc/systemd/system
0755 root root /etc/init.d
0755 root root /etc/conf.d
1777 root root /tmp
1777 root root /var/tmp
1777 root root /dev/shm
